version: '3'
services:
    redis:
        image: 'redis'
        ports: 
          - '6378:6379'
        volumes: 
          - redis:/var/lib/redis/data
    postgres:
        image: 'postgres'
        restart: always
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_PASSWORD=password
        ports:
          - '5433:5432'
        volumes:
          - postgres:/var/lib/postgresql/data
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        container_name: elasticsearch
        environment:
          - discovery.type=single-node
        ports:
          - '9201:9200'
        volumes:
          - elasticsearch:/usr/share/elasticsearch/data
    basic-app:
        build: .
        ports: 
          - '3000:3000'
        environment:
          - REDIS_HOST=redis
          - REDIS_PORT=6378
          - POSTGRES_USER=ubuntu
          - POSTGRES_PASSWORD=password
          - POSTGRES_PORT=5433
        depends_on: 
          - 'redis'
          - 'postgres'
volumes:
    redis:
    postgres:
    elasticsearch: