version: '3'
services:
    redis:
        image: 'redis'
        ports: 
          - '6378:6379'
        volumes: 
          - redis:/var/lib/redis/data
    postgres:
        image: 'postgres'
        restart: always
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_PASSWORD=password
        ports:
          - '5433:5432'
        volumes:
          - postgres:/var/lib/postgresql/data
    basic-app:
        build: .
        ports: 
          - '3000:3000'
        depends_on: 
          - 'redis'
          - 'postgres'
volumes:
    redis:
    postgres: